version: "3.6"
services:
  explainai-database-engine:
    container_name: explainai-database-engine
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  explainai-database-api:
    container_name: explainai-database-api
    image: hasura/graphql-engine:v2.19.0-ce.cli-migrations-v3
    ports:
      - "8080:8080"
    depends_on:
      - "explainai-database-engine"
    restart: always
    volumes:
      - ./database/migrations:/hasura-migrations
      - ./database/metadata:/hasura-metadata
    environment:
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: admin_secret
      DATABASE_URL: postgres://postgres:postgrespassword@explainai-database-engine:5432/postgres
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@explainai-database-engine:5432/postgres
  explainai-api:
    container_name: explainai-api
    depends_on:
      - "explainai-database-engine"
    restart: always
    volumes:
      - api:/api
    environment:
      DB_ENDPOINT: "http://explainai-database-api:8080"
      DB_SECRET: "admin_secret"
    ports:
      - "4000:4000"
    build: ./api
  explainai-frontend:
    container_name: explainai-frontend
    depends_on:
      - "explainai-api"
    restart: always
    volumes:
      - ./web:/web
      - /web/node_modules
    environment:
      REACT_APP_API_ENDPOINT: "http://localhost:4000"
    ports:
      - "3000:3000"
    build: ./web

volumes:
  db_data:
  api:
