import { ChakraProvider, extendTheme } from "@chakra-ui/react";
import Header from "./components/Header";
import Inner from "./components/Inner";
import "./styles.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MyApp({ Component, pageProps }: any) {
  return (
    <>
      <Header {...pageProps} />
      <Inner>
        <Component {...pageProps} />
      </Inner>
    </>
  );
}

// export default function Layout({
//   children,
//   slug,
//   audience,
// }: {
//   children: React.ReactNode;
//   audience?: string;
//   slug?: string;
// }) {
//   return (
//     <>
//       <Header slug={slug} audience={audience} />
//       <Inner>{children}</Inner>
//     </>
//   );
// }
