import Header from "../components/Header";
import "./styles.css";
import dynamic from "next/dynamic";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function Inner({ children }: any) {
  return <main>{children}</main>;
}

const Splash = dynamic(() => import("../components/Splash"), {
  loading: () => (
    <div
      style={{
        minHeight: 250,
        backgroundColor: "#111",
        position: "relative",
        height: "auto",
      }}
    />
  ),
});

export default function App({ Component, pageProps }: any) {
  return (
    <>
      <Header {...pageProps} />
      {pageProps.page === "groups" && <Splash />}
      <Inner>
        <Component {...pageProps} />
      </Inner>
    </>
  );
}
