import { ChakraProvider, extendTheme } from "@chakra-ui/react";
import Header from "./components/Header";
import Inner from "./components/Inner";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
  slug,
  audience,
}: {
  children: React.ReactNode;
  audience?: string;
  slug?: string;
}) {
  const theme = extendTheme({
    styles: {
      global: {
        "html, body": {
          margin: 0,
          padding: 0,
          backgroundColor: "gray.50",
        },
      },
    },
  });
  return (
    <ChakraProvider theme={theme}>
      <Header slug={slug} audience={audience} />
      <Inner>{children}</Inner>
    </ChakraProvider>
  );
}
