name: Test
on: [push]

defaults:
  run:
    working-directory: web
jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Run all tests
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: |
          npm install
          npm test
  lint_job:
    runs-on: ubuntu-latest
    name: Check linting
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - run: |
          npm install
          npm run lint
