name: Lint

on: [push]

defaults:
  run:
    working-directory: ./web
jobs:
  run-cypress-tests:
    name: Run E2E tests 🧪
    uses: cypress-io/github-action@v5

    name: Run Component tests 🧪
    uses: cypress-io/github-action@v5
    with:
        # we have already installed everything
      install: false
        # to run component tests we need to use "component: true"
      component: true
  # run-linters:
  #   name: Run Linter
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out Git repository
  #       uses: actions/checkout@v3

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 16

  #     - name: install node packages
  #       run: npm ci

  #     - name: Run linter
  #       run: npm run lint

  # run-tests:
  #   name: Run Tests
  #   runs-on: ubuntu-latest
  #   needs: run-linters
  #   steps:
  #     - name: Check out Git repository
  #       uses: actions/checkout@v3

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 16
  #     - name: install node packages
  #       run: npm ci
  #     - name: Run Test
  #       run: npm test
  #       env:
  #         REACT_APP_MEASUREMENT_ID: "measurement-ID"
