name: Test
on: [push]
jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Run all tests
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: |
          cd web
          ls
          npm install
          npm test
  lint_job:
    runs-on: ubuntu-latest
    name: Check linting
    steps:
      - uses: actions/setup-node@v3
      - run: cd web
      - run: npm lint
